dependencies:
  build:
    - ruby:2.6.0

build_targets:
  - name: default
    commands:
      - env
      - ls -lR /opt
      - gem update --system
      - gem install bundler
      - bundle install 
      - bundle exec rake --trace spec

  - name: release
    commands:
      - echo "RELEASE"

ci:
  builds:
    - name: build_gem
      build_target: default
